version: 0.0
os: linux
# files:
#   - source: /
#   - destination: /var/www/html
files:
  - source: /
    destination: /var/www/html
# permissions:
#   permissions-specifications
# hooks:
#   deployment-lifecycle-event-mappings
# remember the coolest thing here is that you can set it to run certain commands before and after a deployment